apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-init
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8080
  initContainers:
  - name: multitool
    image: wbitt/network-multitool
    env:
    - name: HTTP_PORT
      value: "1180"
    - name: HTTPS_PORT
      value: "11443"
    ports:
    - containerPort: 1180
      name: http-port
    - containerPort: 11443
      name: https-port
    resources:
      requests:
        cpu: "1m"
        memory: "20Mi"
    securityContext:
      runAsUser: 0
      capabilities:
        add: ["NET_ADMIN"]
    command: ['sh', '-c', "until nslookup nginx.default.svc.cluster.local; do echo waiting for mydb; sleep 2; done"]