apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-multitool
  name: nginx-multitool
spec:
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-2
    port: 1180
    protocol: TCP
    targetPort: 1180
  - name: port-3
    port: 11443
    protocol: TCP
    targetPort: 11443
  selector:
    app: nginx-multitool
